name: environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - rasterio
  - geopandas=0.6.1
  - gdal
  - glob2
  - numpy
  - requests
  - scikit-learn
  - scikit-image
  - pip
  - matplotlib
  - descartes
  - seaborn
  - pip:
      - jupyter-server-proxy
      - nbserverproxy
      - wget==3.2
      - folium==0.10.0
      - rio-l8qa==0.1.1
      - landsat578==0.4.9
      - fonttools
